// SK AGRO CHEMICAL - Clean Category Master Dataset

export const INITIAL_CATEGORIES = [
  { id: 'cat-1', name: 'Insecticides', slug: 'insecticides', description: 'Fast-acting pest elimination formulations', icon: 'Bug', count: 32 },
  { id: 'cat-2', name: 'Fungicides', slug: 'fungicides', description: 'Broad-spectrum crop disease protection', icon: 'ShieldCheck', count: 24 },
  { id: 'cat-3', name: 'Herbicides', slug: 'herbicides', description: 'Selective & Non-selective weed control solutions', icon: 'Sprout', count: 28 },
  { id: 'cat-4', name: 'PGR', slug: 'pgr', description: 'Plant Growth Regulators & Biostimulants', icon: 'Sparkles', count: 14 },
  { id: 'cat-5', name: 'Fertilizers', slug: 'fertilizers', description: 'Essential crop nutrition & growth stimulants', icon: 'Zap', count: 18 },
  { id: 'cat-6', name: 'Micronutrients', slug: 'micronutrients', description: 'Chelated trace elements for soil health', icon: 'Sun', count: 15 },
];

export const INITIAL_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Imaze Clear',
    product_code: 'SK-HERB-001',
    category_id: 'cat-3',
    category_name: 'Herbicides',
    active_ingredient: 'Imazethapyr 10% SL',
    formulation: 'Soluble Liquid (SL)',
    description: 'Systemic herbicide for effective control of broadleaf weeds and grasses in soybean and groundnut crops.',
    main_image_url: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    packing_sizes: ['100ml', '250ml', '500ml', '1L'],
    asset_count: 8,
    is_favorite: true,
  },
  {
    id: 'prod-2',
    name: 'Mancozeb 75% WG',
    product_code: 'SK-FUNG-002',
    category_id: 'cat-2',
    category_name: 'Fungicides',
    active_ingredient: 'Mancozeb 75% WG',
    formulation: 'Water Dispersible Granules (WG)',
    description: 'Broad-spectrum contact fungicide with protective action against late blight, downy mildew, and leaf spots.',
    main_image_url: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    packing_sizes: ['250g', '500g', '1kg'],
    asset_count: 6,
    is_favorite: false,
  },
  {
    id: 'prod-3',
    name: 'Quizalofop Ethyl 10% EC',
    product_code: 'SK-HERB-003',
    category_id: 'cat-3',
    category_name: 'Herbicides',
    active_ingredient: 'Quizalofop-p-ethyl 10% EC',
    formulation: 'Emulsifiable Concentrate (EC)',
    description: 'Selective post-emergence herbicide for narrow leaf weed control in broadleaf crops.',
    main_image_url: 'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    packing_sizes: ['100ml', '250ml', '500ml', '1L'],
    asset_count: 5,
    is_favorite: true,
  },
  {
    id: 'prod-4',
    name: 'Glufosinate Ammonium 13.5% SL',
    product_code: 'SK-HERB-004',
    category_id: 'cat-3',
    category_name: 'Herbicides',
    active_ingredient: 'Glufosinate Ammonium 13.5% SL',
    formulation: 'Soluble Liquid (SL)',
    description: 'Non-selective contact herbicide for broad-spectrum weed management in non-crop areas & orchards.',
    main_image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb231fc?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    packing_sizes: ['500ml', '1L', '5L'],
    asset_count: 7,
    is_favorite: false,
  },
  {
    id: 'prod-5',
    name: 'Carbendazim + Mancozeb',
    product_code: 'SK-FUNG-005',
    category_id: 'cat-2',
    category_name: 'Fungicides',
    active_ingredient: 'Carbendazim 12% + Mancozeb 63% WP',
    formulation: 'Wettable Powder (WP)',
    description: 'Dual-action systemic & contact fungicide offering protective and curative protection against seed-borne & soil-borne pathogens.',
    main_image_url: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    packing_sizes: ['100g', '250g', '500g', '1kg'],
    asset_count: 9,
    is_favorite: true,
  },
  {
    id: 'prod-6',
    name: 'Zinc EDTA 12%',
    product_code: 'SK-NUTRI-006',
    category_id: 'cat-6',
    category_name: 'Micronutrients',
    active_ingredient: 'Chelated Zinc EDTA 12%',
    formulation: 'Micro-granules',
    description: 'High-purity chelated zinc nutrient for rapid correction of zinc deficiency symptoms in cereals, fruits, and vegetables.',
    main_image_url: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    packing_sizes: ['250g', '500g', '1kg'],
    asset_count: 4,
    is_favorite: false,
  },
  {
    id: 'prod-7',
    name: 'Seaweed Extract Bio-Stimulant',
    product_code: 'SK-PGR-007',
    category_id: 'cat-4',
    category_name: 'PGR',
    active_ingredient: 'Ascophyllum Nodosum Extract 20%',
    formulation: 'Liquid Concentrate',
    description: 'Organic plant growth booster enriched with natural cytokinins, auxins, and trace minerals for abiotic stress resistance.',
    main_image_url: 'https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    packing_sizes: ['250ml', '500ml', '1L', '5L'],
    asset_count: 6,
    is_favorite: false,
  },
  {
    id: 'prod-8',
    name: 'Emamectin Benzoate 5% SG',
    product_code: 'SK-INSECT-008',
    category_id: 'cat-1',
    category_name: 'Insecticides',
    active_ingredient: 'Emamectin Benzoate 5% SG',
    formulation: 'Soluble Granule (SG)',
    description: 'Modern translaminar insecticide for superior control of bollworms, stem borers, and leaf folders in cotton and paddy.',
    main_image_url: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    packing_sizes: ['10g', '50g', '100g', '250g', '500g'],
    asset_count: 7,
    is_favorite: true,
  }
];

export const INITIAL_ASSETS = [
  // Imaze Clear Assets
  {
    id: 'asset-101',
    product_id: 'prod-1',
    product_name: 'Imaze Clear',
    asset_type: 'Packing',
    name: 'Imaze Clear 500ml Bottle Photo - High Res',
    packing_size: '500ml',
    file_url: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&q=80&w=1200',
    preview_url: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&q=80&w=400',
    gdrive_file_id: '1A2b3C4d5E6f7G8h9I0j',
    file_type: 'image/png',
    file_size: '4.2 MB',
    description: 'Studio white background 500ml HDPE bottle render with gloss label.',
    created_at: '2026-08-01T10:30:00Z',
    is_favorite: true,
  },
  {
    id: 'asset-102',
    product_id: 'prod-1',
    product_name: 'Imaze Clear',
    asset_type: 'Packing',
    name: 'Imaze Clear 1L Bottle Photo - Front & Back',
    packing_size: '1L',
    file_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=1200',
    preview_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400',
    gdrive_file_id: '2B3c4D5e6F7g8H9i0J1k',
    file_type: 'image/jpeg',
    file_size: '3.8 MB',
    description: '1 Liter bulk master bottle photo with batch stamp box.',
    created_at: '2026-08-01T11:00:00Z',
    is_favorite: false,
  },
  {
    id: 'asset-103',
    product_id: 'prod-1',
    product_name: 'Imaze Clear',
    asset_type: 'Label',
    name: 'Imaze Clear 500ml High Quality Print Label PDF',
    packing_size: '500ml',
    file_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1200',
    preview_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=400',
    gdrive_file_id: '3C4d5E6f7G8h9I0j1K2l',
    file_type: 'application/pdf',
    file_size: '12.4 MB',
    description: 'Approved statutory front & back foil label design with CIB registration number.',
    created_at: '2026-08-02T14:20:00Z',
    is_favorite: true,
  },
  {
    id: 'asset-104',
    product_id: 'prod-1',
    product_name: 'Imaze Clear',
    asset_type: 'Marketing',
    name: 'Imaze Clear Farmer Poster Banner 6x3 ft',
    packing_size: 'All Sizes',
    file_url: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&q=80&w=1200',
    preview_url: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&q=80&w=400',
    gdrive_file_id: '4D5e6F7g8H9i0J1k2L3m',
    file_type: 'image/jpeg',
    file_size: '8.1 MB',
    description: 'Dealer counter banner featuring green field result and dosage table.',
    created_at: '2026-08-03T09:15:00Z',
    is_favorite: false,
  },
  {
    id: 'asset-105',
    product_id: 'prod-1',
    product_name: 'Imaze Clear',
    asset_type: 'Document',
    name: 'Imaze Clear Technical Brochure & Dosage Chart',
    packing_size: 'All Sizes',
    file_url: 'https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&q=80&w=1200',
    preview_url: 'https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&q=80&w=400',
    gdrive_file_id: '5E6f7G8h9I0j1K2l3M4n',
    file_type: 'application/pdf',
    file_size: '2.5 MB',
    description: '4-page product folder detailing application timing and safety precautions.',
    created_at: '2026-08-04T16:00:00Z',
    is_favorite: false,
  },

  // Mancozeb 75% WG Assets
  {
    id: 'asset-201',
    product_id: 'prod-2',
    product_name: 'Mancozeb 75% WG',
    asset_type: 'Packing',
    name: 'Mancozeb 500g Metallic Pouch Photo',
    packing_size: '500g',
    file_url: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&q=80&w=1200',
    preview_url: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&q=80&w=400',
    gdrive_file_id: '6F7g8H9i0J1k2L3m4N5o',
    file_type: 'image/png',
    file_size: '5.1 MB',
    description: '3D render of 500g standing zip pouch with tear notch.',
    created_at: '2026-08-05T12:00:00Z',
    is_favorite: false,
  },
  {
    id: 'asset-202',
    product_id: 'prod-2',
    product_name: 'Mancozeb 75% WG',
    asset_type: 'Material',
    name: 'Mancozeb Dispersible Micro-Granules Close-up',
    packing_size: '500g',
    file_url: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=1200',
    preview_url: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=400',
    gdrive_file_id: '7G8h9I0j1K2l3M4n5O6p',
    file_type: 'image/jpeg',
    file_size: '6.7 MB',
    description: 'Laboratory macro photograph demonstrating rapid water solubility.',
    created_at: '2026-08-06T15:45:00Z',
    is_favorite: true,
  },

  // Emamectin Benzoate Assets
  {
    id: 'asset-301',
    product_id: 'prod-8',
    product_name: 'Emamectin Benzoate 5% SG',
    asset_type: 'Packing',
    name: 'Emamectin Benzoate 100g Laminated Pouch',
    packing_size: '100g',
    file_url: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&q=80&w=1200',
    preview_url: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&q=80&w=400',
    gdrive_file_id: '8H9i0J1k2L3m4N5o6P7q',
    file_type: 'image/png',
    file_size: '3.1 MB',
    description: 'High barrier silver laminate pouch render with holographic brand seal.',
    created_at: '2026-08-07T11:10:00Z',
    is_favorite: true,
  }
];
